/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-4-30: 12h:54m
**
*/

/* ATSextcode_beg() */
// COMMENT_line

var
theUps = $("#up").asEventStream("click")
var
theDns = $("#down").asEventStream("click")
val
thePc = $("#piece").asEventStream("onselect")
// COMMENT_line

var theCounts = 0
var theRes = 0
// COMMENT_line

/* ATSextcode_end() */

var statmp0

var statmp2

var statmp4

var statmp5

var statmp11

var statmp13

function
__patsfun_0__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_0(arg0); }];
}


function
__patsfun_1__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_1(arg0); }];
}


function
__patsfun_2__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_2(arg0, arg1); }];
}


function
__patsfun_3__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_3(arg0); }];
}


function
__patsfun_4__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_4(arg0, arg1); }];
}


function
__patsfun_0(arg0)
{
//
// knd = 0
  var tmpret1
//
  // __patsflab___patsfun_0
  tmpret1 = 1;
  return tmpret1;
} // end-of-function


function
__patsfun_1(arg0)
{
//
// knd = 0
  var tmpret3
//
  // __patsflab___patsfun_1
  tmpret3 = ats2jspre_neg_int0(1);
  return tmpret3;
} // end-of-function


function
__patsfun_2(arg0, arg1)
{
//
// knd = 0
  var tmpret6
  var tmp7
  var tmp8
  var tmp9
  var tmp10
//
  // __patsflab___patsfun_2
  tmp8 = ats2jspre_add_int0_int0(arg0, arg1);
  tmp7 = ats2jspre_lt_int0_int0(tmp8, 0);
  if(tmp7) {
    tmpret6 = 0;
  } else {
    tmp10 = ats2jspre_add_int0_int0(arg0, arg1);
    tmp9 = ats2jspre_gt_int0_int0(tmp10, 9);
    if(tmp9) {
      tmpret6 = 9;
    } else {
      tmpret6 = ats2jspre_add_int0_int0(arg0, arg1);
    } // endif
  } // endif
  return tmpret6;
} // end-of-function


function
__patsfun_3(arg0)
{
//
// knd = 0
  var tmpret12
//
  // __patsflab___patsfun_3
  tmpret12 = arg0;
  return tmpret12;
} // end-of-function


function
__patsfun_4(arg0, arg1)
{
//
// knd = 0
  var tmpret14
//
  // __patsflab___patsfun_4
  tmpret14 = arg1;
  return tmpret14;
} // end-of-function

// dynloadflag_init
var _057_home_057_grad3_057_junx_057_project_057_animation_056_dats__dynloadflag = 0;

function
_057_home_057_grad3_057_junx_057_project_057_animation_056_dats__dynload()
{
//
// knd = 0
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_grad3_057_junx_057_project_057_animation_056_dats__dynloadflag(50))
  if(ATSCKiseqz(_057_home_057_grad3_057_junx_057_project_057_animation_056_dats__dynloadflag)) {
    _057_home_057_grad3_057_junx_057_project_057_animation_056_dats__dynloadflag = 1 ; // flag is set
    statmp0 = ats2js_bacon_EStream_map(theUps, __patsfun_0__closurerize());
    statmp2 = ats2js_bacon_EStream_map(theDns, __patsfun_1__closurerize());
    statmp4 = ats2js_bacon_EStream_merge2(statmp0, statmp2);
    statmp5 = ats2js_bacon_EStream_scan(statmp4, 0, __patsfun_2__closurerize());
    theCounts = statmp5;
    statmp11 = ats2js_bacon_EStream_map(thePc, __patsfun_3__closurerize());
    statmp13 = ats2js_bacon_EStream_scan(statmp11, 0, __patsfun_4__closurerize());
    theRes = statmp13;
  } // endif
  return/*_void*/;
} // end-of-function


function
my_dynload()
{
//
// knd = 0
//
  _057_home_057_grad3_057_junx_057_project_057_animation_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
// COMMENT_line

function
Counter_initize()
{
  var _ = my_dynload()
  var _ = theCounts.assign($("#counter"), "text")
	var _ = theRes.assign($("#res"), "text")
}
// COMMENT_line

jQuery(document).ready(function(){Counter_initize();});
// COMMENT_line

/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
